import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navigation from "@/components/Navigation";
import Provider from "@/redux/provider";
const inter = Inter({ subsets: ["latin"] });

import SessionProviderWrapper from "./sessionProviderWrapper";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, session }: { children: React.ReactNode; session: any }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProviderWrapper session={session}>
					<Navigation />
					{children}
				</SessionProviderWrapper>
			</body>
		</html>
	);
}
